baseURL = 'https://notifuturo.com/'
languageCode = 'en-us'
title = 'NotiFuturo'
theme = "PaperMod"
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
  [markup.goldmark.renderer.linkAttributes]
    href = "^(http|https)://"
    target = "_blank"
    rel = "noopener noreferrer"
